# syntax=docker/dockerfile:1
FROM node:24.18.0-bookworm-slim

ENV COREPACK_HOME=/usr/local/share/corepack
RUN corepack enable && corepack prepare pnpm@11.7.0 --activate
WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile

ARG APP
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_OPS_URL
ARG NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=false
ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_CUSTOMER_API_URL
ARG NEXT_PUBLIC_CUSTOMER_API_ENABLED=false
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_OPS_URL=$NEXT_PUBLIC_OPS_URL \
    NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=$NEXT_PUBLIC_GOOGLE_AUTH_ENABLED \
    NEXT_PUBLIC_WHATSAPP_NUMBER=$NEXT_PUBLIC_WHATSAPP_NUMBER \
    NEXT_PUBLIC_CUSTOMER_API_URL=$NEXT_PUBLIC_CUSTOMER_API_URL \
    NEXT_PUBLIC_CUSTOMER_API_ENABLED=$NEXT_PUBLIC_CUSTOMER_API_ENABLED
RUN test -n "$APP" && pnpm turbo run build --filter="@giromesa/$APP"
RUN mkdir -p /app/data/media && chown -R node:node /app

ENV APP=$APP
ENV NODE_ENV=production
USER node

EXPOSE 3100 3101 3200
CMD ["sh", "-c", "exec pnpm --filter \"@giromesa/$APP\" start"]
