# syntax=docker/dockerfile:1@sha256:ecfaec9ed6d810b56388c508f4121597bfbba70d41a6dfeee4d8cad5f295fc32
FROM node:24.18.0-bookworm-slim@sha256:6f7b03f7c2c8e2e784dcf9295400527b9b1270fd37b7e9a7285cf83b6951452d

ENV COREPACK_HOME=/usr/local/share/corepack
RUN corepack enable && corepack prepare pnpm@11.7.0 --activate
WORKDIR /app

COPY . .
RUN pnpm install --frozen-lockfile

ARG APP
ARG NEXT_PUBLIC_API_URL
ARG NEXT_PUBLIC_OPS_URL
ARG NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=false
ARG NEXT_PUBLIC_WHATSAPP_NUMBER
ARG NEXT_PUBLIC_CUSTOMER_API_URL
ARG NEXT_PUBLIC_CUSTOMER_API_ENABLED=false
ARG NEXT_PUBLIC_DEMO_HUB_ACK=false
ARG CUSTOMER_QA_DEMO_SLUG=demo
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL \
    NEXT_PUBLIC_OPS_URL=$NEXT_PUBLIC_OPS_URL \
    NEXT_PUBLIC_GOOGLE_AUTH_ENABLED=$NEXT_PUBLIC_GOOGLE_AUTH_ENABLED \
    NEXT_PUBLIC_WHATSAPP_NUMBER=$NEXT_PUBLIC_WHATSAPP_NUMBER \
    NEXT_PUBLIC_CUSTOMER_API_URL=$NEXT_PUBLIC_CUSTOMER_API_URL \
    NEXT_PUBLIC_CUSTOMER_API_ENABLED=$NEXT_PUBLIC_CUSTOMER_API_ENABLED \
    NEXT_PUBLIC_DEMO_HUB_ACK=$NEXT_PUBLIC_DEMO_HUB_ACK \
    CUSTOMER_QA_DEMO_SLUG=$CUSTOMER_QA_DEMO_SLUG
RUN test -n "$APP" && pnpm turbo run build --filter="@giromesa/$APP"
RUN chown -R node:node "/app/apps/$APP"

ENV APP=$APP
ENV NODE_ENV=production
USER node

EXPOSE 3100 3101 3200
CMD ["sh", "-c", "exec pnpm --filter \"@giromesa/$APP\" start"]
