ALTER TABLE "management_inventory_count_session_lines" DROP CONSTRAINT "management_inventory_count_session_lines_values_check";--> statement-breakpoint
DROP INDEX "management_nfe_imports_access_key_unique";--> statement-breakpoint
ALTER TABLE "management_inventory_count_session_lines" ADD COLUMN "expected_balance_version" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "management_inventory_count_session_lines" ALTER COLUMN "expected_balance_version" DROP DEFAULT;--> statement-breakpoint
ALTER TABLE "management_inventory_transfers" ADD COLUMN "unit_cost_cents" integer;--> statement-breakpoint
CREATE UNIQUE INDEX "management_inventory_count_sessions_active_location_unique" ON "management_inventory_count_sessions" USING btree ("organization_id","unit_id","location_id") WHERE "management_inventory_count_sessions"."status" in ('open', 'submitted');--> statement-breakpoint
CREATE UNIQUE INDEX "management_nfe_imports_access_key_unique" ON "management_nfe_imports" USING btree ("access_key");--> statement-breakpoint
ALTER TABLE "management_inventory_count_session_lines" ADD CONSTRAINT "management_inventory_count_session_lines_values_check" CHECK ("management_inventory_count_session_lines"."expected_quantity" >= 0 and "management_inventory_count_session_lines"."expected_balance_version" > 0 and ("management_inventory_count_session_lines"."counted_quantity" is null or "management_inventory_count_session_lines"."counted_quantity" >= 0) and (("management_inventory_count_session_lines"."counted_quantity" is null and "management_inventory_count_session_lines"."difference_quantity" is null) or ("management_inventory_count_session_lines"."counted_quantity" is not null and "management_inventory_count_session_lines"."difference_quantity" = "management_inventory_count_session_lines"."counted_quantity" - "management_inventory_count_session_lines"."expected_quantity")));--> statement-breakpoint
ALTER TABLE "management_inventory_transfers" ADD CONSTRAINT "management_inventory_transfers_cost_check" CHECK ("management_inventory_transfers"."unit_cost_cents" is null or "management_inventory_transfers"."unit_cost_cents" >= 0);
